version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7-jessie-node-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install module
          command: |
            sudo apt-get install \
              python-dev libgmp-dev libmpfr-dev libmpc-dev python-pip
            mkdir -p ./venv
            virtualenv ./venv
            . venv/bin/activate
            python setup.py install

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python setup.py test
