version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.12

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install module
          command: python setup.py install

      - run:
          name: run tests
          command: python setup.py test
